### ISSUE TITLE
Not able to build project after adding package

### ISSUE THREAD

**Issue by SanchitSahu** [zenkkor/ngx-credit-cards#11]
The package installs successfully but not able to run my project after adding this.

Initially, I got the error mentioned in #10 but that fixed after using the code mentioned in ticket.

Post that when when I can trying to build the project, I see the below error:

```
ERROR in Error: NgXCreditCardsModule is not an NgModule
    at _getNgModuleMetadata (/home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (/home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/sanchit/projects/bevvi-web/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/sanchit/projects/bevvi-web/node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/sanchit/projects/bevvi-web/node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by Dmonika04** [comment]
I am facing the same error. Any solution?
